# Generated by Django 5.1.15 on 2026-09-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_admin_role_to_owner'),
        ('catalog', '0018_groceryitemprice_promo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='default_excluded_stores',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_household_defaults', to='catalog.store'),
        ),
    ]
