# Generated by Django 5.1.15 on 2026-08-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
