# Generated by Django 5.1.15 on 2026-08-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_groceryitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='pieces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
