# Generated by Django 5.1.15 on 2026-08-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_copy_size_to_grams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='size',
        ),
    ]
