# Generated by Django 5.1.15 on 2026-08-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_groceryitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='milliliters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
