# Generated by Django 5.1.15 on 2026-08-31 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_seed_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='store_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grocery_items', to='catalog.store'),
        ),
    ]
