# Generated by Django 5.1.15 on 2026-08-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_sainsburys'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='aisle',
            field=models.CharField(blank=True, choices=[('fruit_veg', 'Fruit & Veg'), ('bakery', 'Bakery'), ('meat_fish', 'Meat & Fish'), ('dairy_eggs', 'Dairy & Eggs'), ('chilled_ready_meals', 'Chilled & Ready Meals'), ('frozen', 'Frozen'), ('tins_packets', 'Tins & Packets'), ('pasta_rice_world_foods', 'Pasta Rice & World Foods'), ('sauces_oils_seasonings', 'Sauces Oils & Seasonings'), ('breakfast_spreads', 'Breakfast & Spreads'), ('snacks_sweets', 'Snacks & Sweets'), ('tea_coffee_soft_drinks', 'Tea Coffee & Soft Drinks'), ('alcohol', 'Alcohol'), ('free_from_vegan', 'Free From & Vegan'), ('baby_pet', 'Baby & Pet'), ('household_cleaning', 'Household & Cleaning'), ('toiletries_health', 'Toiletries & Health')], max_length=30),
        ),
    ]
