# Generated by Django 5.1.15 on 2026-09-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_groceryitem_aisle'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='trolley_url',
            field=models.URLField(blank=True),
        ),
    ]
