# Generated by Django 5.1.15 on 2026-08-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0002_recipe_meal_type_recipe_source_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealslot',
            name='recipe',
        ),
        migrations.AddField(
            model_name='mealslot',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='meal_slots', to='mealplanner.recipe'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='week_start',
            field=models.DateField(),
        ),
    ]
