# Generated by Django 5.1.15 on 2026-08-30 16:27

import mealplanner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0003_remove_mealslot_recipe_mealslot_recipes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', validators=[mealplanner.models.validate_recipe_image_size]),
        ),
    ]
