# Generated by Django 5.1.15 on 2026-08-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0004_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
