# Generated by Django 5.1.15 on 2026-08-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0006_copy_image_files_to_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
