# Generated by Django 5.1.15 on 2026-08-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0007_remove_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='pieces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
