# Generated by Django 5.1.15 on 2026-08-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0009_copy_quantity_to_grams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity',
        ),
    ]
