# Generated by Django 5.1.15 on 2026-08-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0010_remove_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='milliliters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
