# Generated by Django 5.1.15 on 2026-08-31 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_sainsburys'),
        ('mealplanner', '0013_alter_recipe_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredientStoreOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grocery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredient_options', to='catalog.groceryitem')),
                ('recipe_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_options', to='mealplanner.recipeingredient')),
                ('store', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='catalog.store')),
            ],
            options={
                'unique_together': {('recipe_ingredient', 'store')},
            },
        ),
    ]
