# Generated by Django 5.1.15 on 2026-08-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0015_migrate_grocery_item_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='grocery_item',
        ),
    ]
