# Generated by Django 5.1.15 on 2026-08-31 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0017_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='shopping_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mealplanner.shoppinglist'),
        ),
    ]
