# Generated by Django 5.1.15 on 2026-08-31 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_sainsburys'),
        ('mealplanner', '0020_finalize_shoppinglistitem_shopping_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='grocery_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_items', to='catalog.groceryitem'),
        ),
    ]
