# Generated by Django 5.1.15 on 2026-08-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0021_shoppinglistitem_grocery_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='milliliters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='pieces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
