# Generated by Django 5.1.15 on 2026-08-31 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0023_parse_and_dedupe_shopping_list_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='quantity',
        ),
    ]
