# Generated by Django 5.1.15 on 2026-09-05 15:19

import django.db.models.deletion
import mealplanner.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_household_default_excluded_stores'),
        ('catalog', '0018_groceryitemprice_promo_price'),
        ('mealplanner', '0031_shoppinglist_excluded_stores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essentials', to='accounts.household')),
            ],
            options={
                'verbose_name_plural': 'essentials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EssentialsItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('grams', models.PositiveIntegerField(blank=True, null=True)),
                ('pieces', models.PositiveIntegerField(blank=True, null=True)),
                ('milliliters', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('essentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mealplanner.essentials')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=(mealplanner.models.QuantityMatchMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EssentialsItemGroceryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('essentials_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_matches', to='mealplanner.essentialsitem')),
                ('grocery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essentials_item_matches', to='catalog.groceryitem')),
            ],
            options={
                'unique_together': {('essentials_item', 'grocery_item')},
            },
        ),
    ]
