# Generated by Django 5.1.15 on 2026-09-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0032_essentials_essentialsitem_essentialsitemgroceryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='packs_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
